"""fill out models

Revision ID: affff7a7bb5d
Revises: 15db49d85e47
Create Date: 2023-07-27 14:29:32.307319

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'affff7a7bb5d'
down_revision = '15db49d85e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.FLOAT(),
               type_=sa.String(),
               existing_nullable=True)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('menuitems', schema=None) as batch_op:
        batch_op.alter_column('price',
               existing_type=sa.String(),
               type_=sa.FLOAT(),
               existing_nullable=True)

    # ### end Alembic commands ###
